export const CATEGORY_PAGE_CONFIG = [
  // ───── DARAZ (real category pages for focused results) ─────
  {
    store: 'Daraz',
    title: 'Mobile Phones',
    url: 'https://www.daraz.pk/catalog?q=Smart%20Phones',
    keywords: ['mobile', 'phone', 'smartphone', 'android phone', 'iphone'],
  },
  {
    store: 'Daraz',
    title: 'Mobile Accessories',
    url: 'https://www.daraz.pk/catalog?q=Mobile%20Accessories',
    keywords: ['mobile accessories', 'phone accessories', 'charger', 'cable', 'power bank', 'screen protector', 'phone case'],
  },
  {
    store: 'Daraz',
    title: 'Laptops',
    url: 'https://www.daraz.pk/laptops/',
    keywords: ['laptop', 'notebook', 'computer', 'pc', 'gaming laptop', 'macbook'],
  },
  {
    store: 'Daraz',
    title: 'Tablets',
    url: 'https://www.daraz.pk/tablets/',
    keywords: ['tablet', 'ipad', 'tab', 'samsung tab'],
  },
  {
    store: 'Daraz',
    title: 'Televisions',
    url: 'https://www.daraz.pk/televisions/',
    keywords: ['tv', 'television', 'smart tv', 'led tv', 'oled'],
  },
  {
    store: 'Daraz',
    title: 'Headphones & Headsets',
    url: 'https://www.daraz.pk/catalog?q=Headphones%20%26%20Headsets',
    keywords: ['headphones', 'headset', 'earphones', 'earbuds', 'handsfree', 'airpods', 'bluetooth headphones', 'wireless earbuds', 'gaming headset'],
  },
  {
    store: 'Daraz',
    title: 'Portable Speakers',
    url: 'https://www.daraz.pk/catalog?q=Portable%20Speakers',
    keywords: ['speaker', 'bluetooth speaker', 'portable speaker', 'sound system', 'wireless speaker'],
  },
  {
    store: 'Daraz',
    title: 'Smart Watches',
    url: 'https://www.daraz.pk/smart-watches/',
    keywords: ['smart watch', 'smartwatch', 'fitness band', 'fitness tracker', 'wearable'],
  },
  {
    store: 'Daraz',
    title: 'Cameras & Drones',
    url: 'https://www.daraz.pk/cameras/',
    keywords: ['camera', 'dslr', 'drone', 'photography', 'video camera', 'mirrorless'],
  },
  {
    store: 'Daraz',
    title: 'Gaming Consoles',
    url: 'https://www.daraz.pk/gaming-consoles/',
    keywords: ['gaming', 'console', 'playstation', 'ps5', 'xbox', 'nintendo', 'gaming accessories'],
  },
  {
    store: 'Daraz',
    title: 'Kitchen Appliances',
    url: 'https://www.daraz.pk/kitchen-appliances/',
    keywords: ['kitchen appliances', 'blender', 'juicer', 'oven', 'microwave', 'cooking appliances', 'air fryer'],
  },
  {
    store: 'Daraz',
    title: 'Home Appliances',
    url: 'https://www.daraz.pk/home-appliances/',
    keywords: ['home appliance', 'washing machine', 'iron', 'vacuum cleaner', 'fan', 'heater', 'air conditioner', 'ac'],
  },
  {
    store: 'Daraz',
    title: 'Refrigerators',
    url: 'https://www.daraz.pk/refrigerators/',
    keywords: ['refrigerator', 'fridge', 'freezer'],
  },
  {
    store: 'Daraz',
    title: 'Beauty & Makeup',
    url: 'https://www.daraz.pk/catalog?q=Makeup',
    keywords: ['makeup', 'cosmetics', 'beauty products', 'foundation', 'lipstick'],
  },
  {
    store: 'Daraz',
    title: 'Skin Care',
    url: 'https://www.daraz.pk/catalog?q=Skin%20Care',
    keywords: ['skincare', 'skin care', 'face wash', 'cream', 'serum', 'moisturizer', 'sunscreen'],
  },
  {
    store: 'Daraz',
    title: 'Hair Care',
    url: 'https://www.daraz.pk/catalog?q=Hair%20Care',
    keywords: ['hair care', 'shampoo', 'conditioner', 'hair oil', 'hair treatment'],
  },
  {
    store: 'Daraz',
    title: 'Fragrances',
    url: 'https://www.daraz.pk/fragrances/',
    keywords: ['perfume', 'fragrance', 'cologne', 'body spray', 'attar'],
  },
  {
    store: 'Daraz',
    title: 'Men Clothing',
    url: 'https://www.daraz.pk/mens-clothing/',
    keywords: ['men clothing', 'shirts', 'tshirts', 'jeans', 'pants', 'mens fashion', 'shalwar kameez'],
  },
  {
    store: 'Daraz',
    title: 'Women Clothing',
    url: 'https://www.daraz.pk/womens-clothing/',
    keywords: ['women clothing', 'dress', 'skirts', 'fashion', 'ladies dress', 'kurti', 'lawn'],
  },
  {
    store: 'Daraz',
    title: 'Shoes',
    url: 'https://www.daraz.pk/shoes/',
    keywords: ['shoes', 'sneakers', 'sports shoes', 'running shoes', 'sandals', 'heels', 'chappal'],
  },
  {
    store: 'Daraz',
    title: 'Bags & Luggage',
    url: 'https://www.daraz.pk/bags/',
    keywords: ['bag', 'handbag', 'backpack', 'luggage', 'wallet', 'purse'],
  },
  {
    store: 'Daraz',
    title: 'Watches',
    url: 'https://www.daraz.pk/watches/',
    keywords: ['watch', 'wristwatch', 'analog watch', 'digital watch'],
  },
  {
    store: 'Daraz',
    title: 'Groceries',
    url: 'https://www.daraz.pk/catalog?q=Groceries',
    keywords: ['grocery', 'groceries', 'food', 'snacks', 'cooking oil', 'rice', 'flour'],
  },
  {
    store: 'Daraz',
    title: 'Baby Products',
    url: 'https://www.daraz.pk/catalog?q=Baby%20Products',
    keywords: ['baby', 'diaper', 'baby care', 'stroller', 'baby food'],
  },
  {
    store: 'Daraz',
    title: 'Sports & Fitness',
    url: 'https://www.daraz.pk/catalog?q=Sports%20%26%20Fitness',
    keywords: ['sports', 'fitness', 'gym', 'exercise', 'yoga', 'cricket', 'football'],
  },
  {
    store: 'Daraz',
    title: 'Automotive',
    url: 'https://www.daraz.pk/catalog?q=Car%20Accessories',
    keywords: ['car accessories', 'automotive', 'car', 'bike accessories', 'dashcam'],
  },
  {
    store: 'PriceOye',
    url: 'https://priceoye.pk/mobiles',
    title: 'Mobiles',
    keywords: ['mobile', 'phone', 'smartphone', 'cellphone'],
  },
  {
    store: 'PriceOye',
    url: 'https://priceoye.pk/smart-watches',
    title: 'Smart Watches',
    keywords: ['watch', 'smart watch', 'wearable', 'band'],
  },
  {
    store: 'PriceOye',
    url: 'https://priceoye.pk/wireless-earbuds',
    title: 'Wireless Earbuds',
    keywords: ['earbuds', 'earphones', 'headphones', 'audio'],
  },
  {
    store: 'PriceOye',
    url: 'https://priceoye.pk/power-banks',
    title: 'Power Banks',
    keywords: ['power bank', 'charger', 'battery'],
  },
  {
    store: 'PriceOye',
    url: 'https://priceoye.pk/mobiles-accessories',
    title: 'Mobile Accessories',
    keywords: ['mobile accessories', 'phone accessories', 'charger', 'case', 'screen protector'],
  },
  {
    store: 'PriceOye',
    url: 'https://priceoye.pk/air-purifiers',
    title: 'Air Purifiers',
    keywords: ['air purifier', 'air cleaner'],
  },
  {
    store: 'PriceOye',
    url: 'https://priceoye.pk/tv-home-appliances',
    title: 'TV & Home Appliances',
    keywords: ['tv', 'home appliances', 'electronics', 'appliances'],
  },
  {
    store: 'PriceOye',
    url: 'https://priceoye.pk/tablets',
    title: 'Tablets',
    keywords: ['tablet', 'ipad', 'tab'],
  },
  {
    store: 'PriceOye',
    url: 'https://priceoye.pk/personal-cares',
    title: 'Personal Care',
    keywords: ['personal care', 'beauty', 'skincare', 'health'],
  },
  {
    store: 'Naheed',
    url: 'https://www.naheed.pk/groceries-pets',
    title: 'Groceries & Pets',
    keywords: ['groceries', 'pets', 'food', 'pet'],
  },
  {
    store: 'Naheed',
    url: 'https://www.naheed.pk/fresh-st-cafe',
    title: 'Fresh & Café',
    keywords: ['fresh', 'grocery', 'cafe', 'food'],
  },
  {
    store: 'Naheed',
    url: 'https://www.naheed.pk/pharmacy',
    title: 'Pharmacy',
    keywords: ['pharmacy', 'medicine', 'health'],
  },
  {
    store: 'Naheed',
    url: 'https://www.naheed.pk/health-beauty',
    title: 'Health & Beauty',
    keywords: ['health', 'beauty', 'skincare', 'personal care'],
  },
  {
    store: 'Naheed',
    url: 'https://www.naheed.pk/phones-tablets',
    title: 'Phones & Tablets',
    keywords: ['phone', 'tablet', 'mobile', 'smartphone'],
  },
  {
    store: 'Naheed',
    url: 'https://www.naheed.pk/tv-home-appliances',
    title: 'TV & Home Appliances',
    keywords: ['tv', 'appliance', 'home appliances'],
  },
  {
    store: 'Naheed',
    url: 'https://www.naheed.pk/womens-fashion',
    title: 'Women’s Fashion',
    keywords: ['women', 'fashion', 'clothing', 'apparel'],
  },
  {
    store: 'Naheed',
    url: 'https://www.naheed.pk/men-s-fashion',
    title: 'Men’s Fashion',
    keywords: ['men', 'fashion', 'clothing', 'apparel'],
  },
  {
    store: 'Naheed',
    url: 'https://www.naheed.pk/watches-bags-jewellery',
    title: 'Watches, Bags & Jewellery',
    keywords: ['watch', 'bag', 'jewellery', 'accessories'],
  },
  {
    store: 'Naheed',
    url: 'https://www.naheed.pk/books',
    title: 'Books',
    keywords: ['book', 'books', 'reading'],
  },
  {
    store: 'Naheed',
    url: 'https://www.naheed.pk/home-lifestyle',
    title: 'Home & Lifestyle',
    keywords: ['home', 'lifestyle', 'decor'],
  },
  {
    store: 'Naheed',
    url: 'https://www.naheed.pk/medical-nutrition',
    title: 'Medical Nutrition',
    keywords: ['nutrition', 'medical', 'health', 'supplements'],
  },
  {
    store: 'Naheed',
    url: 'https://www.naheed.pk/kids-babies',
    title: 'Kids & Babies',
    keywords: ['kids', 'babies', 'children', 'toys'],
  },
  {
    store: 'Naheed',
    url: 'https://www.naheed.pk/naheed-products',
    title: 'Naheed Products',
    keywords: ['naheed products', 'basics', 'everyday'],
  },
  {
    store: 'Naheed',
    url: 'https://www.naheed.pk/back-to-school',
    title: 'Back to School',
    keywords: ['school', 'stationery', 'back to school'],
  },
  {
    store: 'Shophive',
    url: 'https://www.shophive.com/apple',
    title: 'Apple',
    keywords: ['apple', 'iphone', 'macbook', 'ipad'],
  },
  {
    store: 'Shophive',
    url: 'https://www.shophive.com/mobile-phones',
    title: 'Mobile Phones',
    keywords: ['mobile', 'phone', 'smartphone'],
  },
  {
    store: 'Shophive',
    url: 'https://www.shophive.com/smart-watches',
    title: 'Smart Watches',
    keywords: ['watch', 'smart watch', 'wearable'],
  },
  {
    store: 'Shophive',
    url: 'https://www.shophive.com/tablets',
    title: 'Tablets',
    keywords: ['tablet', 'ipad', 'tab'],
  },
  {
    store: 'Shophive',
    url: 'https://www.shophive.com/laptops-computers',
    title: 'Laptops & Computers',
    keywords: ['laptop', 'computer', 'notebook', 'pc'],
  },
  {
    store: 'Shophive',
    url: 'https://www.shophive.com/tv',
    title: 'TV',
    keywords: ['tv', 'television', 'display'],
  },
  {
    store: 'Shophive',
    url: 'https://www.shophive.com/audio',
    title: 'Audio',
    keywords: ['audio', 'speaker', 'headphone', 'earbuds'],
  },
  {
    store: 'Shophive',
    url: 'https://www.shophive.com/cameras',
    title: 'Cameras',
    keywords: ['camera', 'dslr', 'mirrorless', 'lens'],
  },
  {
    store: 'Shophive',
    url: 'https://www.shophive.com/appliances',
    title: 'Appliances',
    keywords: ['appliance', 'home appliance', 'kitchen'],
  },
  // ───── HIGHFY (Shopify-based beauty store) ─────
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/skin-care-new-main-menu',
    title: 'Skincare',
    keywords: ['skincare', 'skin care', 'face wash', 'serum', 'moisturizer', 'sunscreen', 'cream', 'cleanser', 'toner'],
  },
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/makeup-new-main-menu',
    title: 'Makeup',
    keywords: ['makeup', 'cosmetics', 'foundation', 'lipstick', 'mascara', 'eyeliner', 'blush', 'concealer', 'primer'],
  },
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/hair-care-new-main-menu',
    title: 'Haircare',
    keywords: ['hair care', 'haircare', 'shampoo', 'conditioner', 'hair oil', 'hair mask', 'hair treatment', 'hair serum'],
  },
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/fragrance-new-main-menui',
    title: 'Fragrance',
    keywords: ['perfume', 'fragrance', 'cologne', 'body spray', 'attar', 'deodorant'],
  },
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/personal-care-new-main-menu',
    title: 'Personal Care',
    keywords: ['personal care', 'body wash', 'soap', 'lotion', 'body cream', 'hygiene'],
  },
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/face-sunscreen',
    title: 'Face Sunscreen',
    keywords: ['sunscreen', 'sunblock', 'spf', 'sun protection', 'uv'],
  },
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/face-serum',
    title: 'Face Serum',
    keywords: ['serum', 'face serum', 'vitamin c', 'niacinamide', 'retinol'],
  },
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/lipstick-new',
    title: 'Lipstick',
    keywords: ['lipstick', 'lip tint', 'lip gloss', 'lip color'],
  },
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/foundation-new',
    title: 'Foundation',
    keywords: ['foundation', 'bb cream', 'cc cream', 'base makeup'],
  },
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/mascara-new',
    title: 'Mascara',
    keywords: ['mascara', 'lashes', 'eyelash'],
  },
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/hair-tools-1',
    title: 'Hair Tools',
    keywords: ['hair dryer', 'straightener', 'curler', 'hair tool', 'styling tool'],
  },
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/beauty-tools',
    title: 'Beauty Tools',
    keywords: ['beauty tool', 'brush', 'sponge', 'beauty blender', 'makeup brush'],
  },
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/face-mask-sheets-new',
    title: 'Face Masks & Sheets',
    keywords: ['face mask', 'sheet mask', 'peel off mask', 'clay mask'],
  },
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/shampoos',
    title: 'Shampoos',
    keywords: ['shampoo', 'anti dandruff', 'hair wash'],
  },
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/moisturizer-1',
    title: 'Moisturizer',
    keywords: ['moisturizer', 'moisturiser', 'face cream', 'night cream', 'day cream'],
  },
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/face-toner',
    title: 'Face Toner',
    keywords: ['toner', 'face toner', 'exfoliating toner'],
  },
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/face-wash-cleanser-new',
    title: 'Face Wash & Cleanser',
    keywords: ['face wash', 'cleanser', 'cleansing', 'face cleanser'],
  },
  {
    store: 'Highfy',
    url: 'https://highfy.pk/collections/lip-balm-1',
    title: 'Lip Balm',
    keywords: ['lip balm', 'lip care', 'chapstick'],
  },
];

export function getRelevantCategoryUrls(query) {
  if (!query || !query.trim()) return [];

  const normalizedQuery = query.toLowerCase();
  const queryWords = normalizedQuery.split(/[^a-z0-9]+/).filter(Boolean);

  const matchedUrls = CATEGORY_PAGE_CONFIG.filter((page) => {
    const haystack = [page.title.toLowerCase(), page.store.toLowerCase(), ...(page.keywords || [])].join(' ');
    return queryWords.some((word) => haystack.includes(word));
  }).map((page) => page.url);

  return Array.from(new Set(matchedUrls));
}
